---
# tasks file for agent

- name: Download node_exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /home/vagrant

- name: Unarchive a node_exporter-1.5.0.linux-amd64.tar.gz into /home/vagrant that is already on the remote machine
  ansible.builtin.unarchive:
    src: /home/vagrant/node_exporter-1.5.0.linux-amd64.tar.gz
    dest: /home/vagrant
    remote_src: yes

- name: Ensure group "nodeusr" exists
  ansible.builtin.group:
    name: nodeusr
    state: present

- name: Add the user 'nodeusr' with a bash shell
  ansible.builtin.user:
    name: nodeusr
    shell: /bin/bash
    groups: nodeusr

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/vagrant/node_exporter-1.5.0.linux-amd64/node_exporter
    dest: /usr/local/bin/
    remote_src: yes

- name: Change node_exporter ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: '0777'
  tags: 
    - mode
    - node

- name: Template a file to /etc/systemd/system/node_exporter.service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root

- name: Enable service node_exporter, and not touch the state
  ansible.builtin.service:
    name: node_exporter
    state: restarted
